In [4]:
!conda activate pandas-dev

In [114]:
import sys
sys.path.insert(0, '.')
from pandas.core.groupby.generic import SeriesGroupBy
from pandas.core.series import Series
import numpy as np

In [112]:
s = Series([1,5,6,7])
gr = s.groupby(level=0)

In [13]:
gr.groups

{0: [0], 1: [1], 2: [2], 3: [3]}

In [115]:
s.index = [1,2, 8, np.nan]

In [116]:
s

1.0    1
2.0    5
8.0    6
NaN    7
dtype: int64

In [117]:
s.groupby(level=0)
gr = s.groupby(level=0)
gr.groups

{1.0: [1.0], 2.0: [2.0], 8.0: [8.0]}

In [118]:
gr.grouper.codes

[array([ 0,  1,  2, -1], dtype=int64)]

In [119]:
gr.grouper.group_info

(array([ 0,  1,  2, -1], dtype=int64), array([0, 1, 2]), 3)

In [120]:
gr.grouper.groups

{1.0: [1.0], 2.0: [2.0], 8.0: [8.0]}

In [121]:
gr.grouper.groupings[0].index

Float64Index([1.0, 2.0, 8.0, nan], dtype='float64')

In [61]:
from pandas import  date_range, Timestamp, Grouper, MultiIndex

In [22]:
Timestamp('2019')

Timestamp('2019-01-01 00:00:00')

In [132]:
s.index = [Timestamp('01-01-2020'), Timestamp('01-03-2020'), Timestamp('01-03-2020'), Timestamp('01-05-2020')]

In [153]:
s

2020-01-01    1
2020-01-03    5
2020-01-03    6
2020-01-05    7
dtype: int64

In [161]:
gr = s.groupby(Grouper(freq='1H'))

In [28]:
gr

In [162]:
gr.groups

{Timestamp('2020-01-01 00:00:00', freq='H'): 1,
 Timestamp('2020-01-01 01:00:00', freq='H'): 1,
 Timestamp('2020-01-01 02:00:00', freq='H'): 1,
 Timestamp('2020-01-01 03:00:00', freq='H'): 1,
 Timestamp('2020-01-01 04:00:00', freq='H'): 1,
 Timestamp('2020-01-01 05:00:00', freq='H'): 1,
 Timestamp('2020-01-01 06:00:00', freq='H'): 1,
 Timestamp('2020-01-01 07:00:00', freq='H'): 1,
 Timestamp('2020-01-01 08:00:00', freq='H'): 1,
 Timestamp('2020-01-01 09:00:00', freq='H'): 1,
 Timestamp('2020-01-01 10:00:00', freq='H'): 1,
 Timestamp('2020-01-01 11:00:00', freq='H'): 1,
 Timestamp('2020-01-01 12:00:00', freq='H'): 1,
 Timestamp('2020-01-01 13:00:00', freq='H'): 1,
 Timestamp('2020-01-01 14:00:00', freq='H'): 1,
 Timestamp('2020-01-01 15:00:00', freq='H'): 1,
 Timestamp('2020-01-01 16:00:00', freq='H'): 1,
 Timestamp('2020-01-01 17:00:00', freq='H'): 1,
 Timestamp('2020-01-01 18:00:00', freq='H'): 1,
 Timestamp('2020-01-01 19:00:00', freq='H'): 1,
 Timestamp('2020-01-01 20:00:00', freq='

In [33]:
gr.grouper.group_info

(array([0, 2, 2, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64), 5)

In [150]:
gr.groups.pop(Timestamp('2020-01-01 00:00:00'))

1

In [152]:
gr.grouper.groupings[0].index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')

In [39]:
gr.grouper.binlabels

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')

In [42]:
gr.grouper.bins

array([1, 1, 3, 3, 4], dtype=int64)

In [43]:
gr.grouper.codes_info

array([0, 2, 2, 4], dtype=int64)

In [ ]:
[0,1,1,2]

In [151]:
gr.groups

{Timestamp('2020-01-02 00:00:00', freq='D'): 1,
 Timestamp('2020-01-03 00:00:00', freq='D'): 3,
 Timestamp('2020-01-04 00:00:00', freq='D'): 3,
 Timestamp('2020-01-05 00:00:00', freq='D'): 4}

In [135]:
gr.grouper.groupings

[Grouping(None)]

In [81]:
gr.grouper.levels

[DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
                '2020-01-05'],
               dtype='datetime64[ns]', freq='D')]

In [159]:
gr.grouper.levels[0].pop()

AttributeError: 'DatetimeIndex' object has no attribute 'pop'

In [160]:
gr.value_counts()

[Timestamp('2020-01-01 00:00:00', freq='D'), Timestamp('2020-01-02 00:00:00', freq='D'), Timestamp('2020-01-03 00:00:00', freq='D'), Timestamp('2020-01-04 00:00:00', freq='D'), Timestamp('2020-01-05 00:00:00', freq='D')]
2020-01-01    1
2020-01-02    0
2020-01-03    2
2020-01-04    0
2020-01-05    1
Freq: D, dtype: int64
(array([0, 2, 2, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64), 5)
(array([0, 2, 2, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64), 5)
[0 2 2 4]
[ True  True  True  True] [0 1 2 3]
levels=[DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq=None), Int64Index([1, 5, 6, 7], dtype='int64')]
unique(ids)=array([0, 2, 4], dtype=int64)
used_ids=array([0, 2, 4], dtype=int64)
[array([0, 2, 4], dtype=int64)]


IndexError: index 4 is out of bounds for axis 0 with size 3

In [51]:
gr.grouper.result_index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')

In [156]:
gr.grouper.reconstructed_codes

[array([0, 2, 4], dtype=int64)]

In [136]:
[0,1,2]

AttributeError: 'BinGrouper' object has no attribute 'compressed'

In [83]:
[ping.group_index for ping in gr.grouper.groupings]

[DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
                '2020-01-05'],
               dtype='datetime64[ns]', freq=None)]

In [63]:
i = MultiIndex.from_product([[1,2,3], [4,5,6]])

In [64]:
i

MultiIndex([(1, 4),
            (1, 5),
            (1, 6),
            (2, 4),
            (2, 5),
            (2, 6),
            (3, 4),
            (3, 5),
            (3, 6)],
           )

In [65]:
se = Series(range(9), i)

In [66]:
se

1  4    0
   5    1
   6    2
2  4    3
   5    4
   6    5
3  4    6
   5    7
   6    8
dtype: int64

In [87]:
gr1 = se.groupby(level=[0,1])

In [88]:
gr1.groups

{(1, 4): [(1, 4)], (1, 5): [(1, 5)], (1, 6): [(1, 6)], (2, 4): [(2, 4)], (2, 5): [(2, 5)], (2, 6): [(2, 6)], (3, 4): [(3, 4)], (3, 5): [(3, 5)], (3, 6): [(3, 6)]}

In [89]:
gr1.grouper.group_info

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 9)

In [90]:
gr1.grouper.reconstructed_codes

[array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64)]

In [92]:
[ping.group_index for ping in gr1.grouper.groupings]

[Int64Index([1, 2, 3], dtype='int64'), Int64Index([4, 5, 6], dtype='int64')]

In [95]:
gr1.grouper.codes_info

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [98]:
gr1.grouper.get_group_levels()

[Int64Index([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype='int64'),
 Int64Index([4, 5, 6, 4, 5, 6, 4, 5, 6], dtype='int64')]

In [107]:
gr.grouper.levels

[DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
                '2020-01-05'],
               dtype='datetime64[ns]', freq='D')]

In [129]:
gr1.grouper.groupings

[Grouping(None), Grouping(None)]

In [111]:
gr1.grouper.names

[None, None]

In [73]:
from pandas.core.sorting import compress_group_index

In [74]:
compress_group_index([0,5,6,999])

(array([0, 1, 2, 3], dtype=int64), array([  0,   5,   6, 999], dtype=int64))

In [128]:
gr1.grouper.reconstructed_codes

[array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64)]

In [78]:
s

2020-01-01    1
2020-01-03    5
2020-01-03    6
2020-01-05    7
dtype: int64

In [125]:
gr1.grouper.reconstructed_codes

[array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64)]

In [126]:
[compress_group_index(code) for code in gr1.grouper.reconstructed_codes]

[(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
  array([0, 1, 2], dtype=int64)),
 (array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64),
  array([0, 1, 2], dtype=int64))]

In [124]:
se.index

MultiIndex([(1, 4),
            (1, 5),
            (1, 6),
            (2, 4),
            (2, 5),
            (2, 6),
            (3, 4),
            (3, 5),
            (3, 6)],
           )

In [141]:
int(np.ceil(4.3))

5

NameError: name 'ceil' is not defined

In [142]:
mod

NameError: name 'mod' is not defined

<ufunc 'remainder'>

In [146]:
max(3,4,5,6)

6

In [148]:
imax([1,2,3])

NameError: name 'imax' is not defined

In [166]:
np.zeros([[1,2,3], [4,5,6]])

TypeError: 'list' object cannot be interpreted as an integer

In [169]:
?np.matrix

In [172]:
s.name